### ISSUE TITLE
question: possible to take multiple photos without leaving camera?

### ISSUE THREAD

**Issue by jamesdixon** [mateusfccp/magiceye#6]
Hi there,

Looks like a fantastic package! I was wondering if it's possible to take multiple photos without actually leaving the camera screen?

I'm working on an app where the user may want to take multiple photos at once (similar to iOS burst mode).

Thanks!
James

**Comment by mateusfccp** [comment]
Hi, @jamesdixon!
Thanks for your support!

`magiceye` is, at least currently, only an abstraction on top of the official Flutter `camera` plugin. Although there are ways to make a burst capture of images ([at least on Android](https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession#captureBurst), didn't search much about iOS), these APIs are not exposed to me through their plugin.

Being so, if I am to implement this feature, I would have to (1) wait for them to provide a way to make burst shots in their API or (2) implement by myself through native.

I've been thinking about the possibility of forking or implementing my own camera plugin to be used with `magiceye`, but is not like I have much time...

This being said, I think I can provide a feature where the user can take any arbitrary amount of photos sequentially by providing them through a `Stream` of taken photos, instead of `Future` of one single taken photo (that is the current API). I am going to reason about it.

---

Does this answer your question?

**Comment by jamesdixon** [comment]
@mateusfccp thanks for the thoughtful reply 🙏  Yes, I think even being able to take photos sequentially through a stream would be fantastic.

**Comment by mateusfccp** [comment]
@jamesdixon I am going to open an issue to track this feature and then close this one. Maybe this weekend I can give a look on this.

**Comment by jamesdixon** [comment]
Very cool! Thank you 👍
